In [2]:
import numpy as np
sn, symbol, x, y,z = np.loadtxt('tetraCoord.rtf',unpack = True,
                               dtype = {'names': ('sno','symbol','x','y','z'),
                                                 'formats': ('i4','S2','f4','f4','f4')})
x,y,z

(array([ 3.26 ,  4.046,  5.456,  6.17 ,  5.454,  6.951,  9.758, 11.255,
         3.26 ,  4.047,  5.455,  6.168,  8.341,  8.343,  8.354,  8.362,
        13.432, 12.651, 11.256, 10.544, 13.429, 12.649, 11.256, 10.545],
       dtype=float32),
 array([ 4.411,  5.69 ,  8.127,  9.447,  0.591,  0.632,  0.642,  0.609,
         1.869,  2.324,  3.139,  3.552, 10.672,  9.762,  8.156,  7.352,
         1.873,  2.331,  3.145,  3.55 ,  4.412,  5.692,  8.131,  9.45 ],
       dtype=float32),
 array([0.423, 0.451, 0.448, 0.419, 0.419, 0.455, 0.479, 0.461, 4.015,
        5.21 , 7.509, 8.763, 4.005, 5.196, 7.5  , 8.764, 4.017, 5.211,
        7.51 , 8.766, 0.427, 0.458, 0.458, 0.421], dtype=float32))

In [3]:
coord = np.array([x,y,z])
coord1 = coord.T
# Zrarray = np.array([coord1[17],coord1[18],coord1[19],coord1[20],coord1
coord1

array([[ 3.26 ,  4.411,  0.423],
       [ 4.046,  5.69 ,  0.451],
       [ 5.456,  8.127,  0.448],
       [ 6.17 ,  9.447,  0.419],
       [ 5.454,  0.591,  0.419],
       [ 6.951,  0.632,  0.455],
       [ 9.758,  0.642,  0.479],
       [11.255,  0.609,  0.461],
       [ 3.26 ,  1.869,  4.015],
       [ 4.047,  2.324,  5.21 ],
       [ 5.455,  3.139,  7.509],
       [ 6.168,  3.552,  8.763],
       [ 8.341, 10.672,  4.005],
       [ 8.343,  9.762,  5.196],
       [ 8.354,  8.156,  7.5  ],
       [ 8.362,  7.352,  8.764],
       [13.432,  1.873,  4.017],
       [12.651,  2.331,  5.211],
       [11.256,  3.145,  7.51 ],
       [10.544,  3.55 ,  8.766],
       [13.429,  4.412,  0.427],
       [12.649,  5.692,  0.458],
       [11.256,  8.131,  0.458],
       [10.545,  9.45 ,  0.421]], dtype=float32)

In [4]:
xmean = np.mean(x)
ymean = np.mean(y)
zmean = np.mean(z)
COM = np.array([xmean,ymean,zmean])
COM

array([8.351749 , 4.814958 , 3.4077082], dtype=float32)

In [5]:
from ase.atom import Atom
atom = Atom('Zr',[COM])
atom


Atom('Zr', [array([8.35174942, 4.8149581 , 3.40770817])])

In [14]:
# m = 91.224*3 + 16
m = [91.224, 91.224, 91.224, 16]

In [23]:
sn1, sym1, x1, y1, z1 = np.loadtxt('tetrasecondpore-trial.txt',unpack = True,
                               dtype = {'names': ('sno','symbol','x','y','z'),
                                                 'formats': ('i4','S2','f4','f4','f4')})
x1,y1,z1
X1 = x1.T
Y1 = y1.T
Z1 = z1.T
X1

array([15.091, 20.727, 20.727, 27.928], dtype=float32)

In [25]:
xmean1 = sum((X1*m))/sum(m)
ymean1 = sum((Y1*m))/sum(m)
zmean1 = sum((Z1*m))/sum(m)
COM1 = np.array([xmean1,ymean1,zmean1])
COM1
# xmean1

array([19.34984709, 11.16503836,  7.89855107])

### Corrected second tetrahedral pore 

In [9]:
# # !pip install shutil
# !pip install --upgrade pip